# Generated by Django 5.1.4 on 2024-12-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('ban_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='banner_images/img')),
            ],
        ),
    ]
